In [ ]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
import statsmodels.api as sm

In [ ]:
data = pd.read_excel('/content/drive/MyDrive/dataset/Data for Day of the week effect.xlsx', sheet_name=None)

In [ ]:
excel={}

for sheet_name, df in data.items():
  excel[sheet_name]=df

excel['BSE']

          Date      Open      High       Low     Close     Average
0   2021-04-01  49868.53  50092.48  49478.53  50029.83  49867.3425
1   2021-04-05  50020.91  50028.67  48580.80  49159.32  49447.4250
2   2021-04-06  49441.13  49582.26  48936.35  49201.39  49290.2825
3   2021-04-07  49277.09  49900.13  49093.90  49661.76  49483.2200
4   2021-04-08  49885.26  50118.08  49581.61  49746.21  49832.7900
..         ...       ...       ...       ...       ...         ...
243 2022-03-25  57801.72  57845.37  57100.24  57362.20  57527.3825
244 2022-03-28  57472.72  57638.34  56825.09  57593.49  57382.4100
245 2022-03-29  57814.76  58001.53  57639.35  57943.65  57849.8225
246 2022-03-30  58362.85  58727.78  58176.00  58683.99  58487.6550
247 2022-03-31  58779.71  58890.92  58485.79  58568.51  58681.2325

[248 rows x 6 columns]

In [ ]:
for sheet_name, df in data.items():
  df['Date'] = pd.to_datetime(df['Date'])
  df['Day_of_week'] = df['Date'].dt.dayofweek
  if sheet_name == "BSE":
    df['Return'] = np.log(df['Close']).diff()
  else:
    df['Return'] = np.log(df['Adj Close']).diff()
  df['Return'].fillna(0,inplace=True)
  excel[sheet_name]=df
  print("Sheet name:", sheet_name)
  print(excel[sheet_name]['Return'])
  print('\n')

Sheet name: BSE
0      0.000000
1     -0.017553
2      0.000855
3      0.009313
4      0.001699
         ...
243   -0.004062
244    0.004024
245    0.006061
246    0.012696
247   -0.001970
Name: Return, Length: 248, dtype: float64


Sheet name: ONGC
0      0.000000
1     -0.008662
2      0.004822
3      0.006711
4     -0.010084
         ...
242    0.010480
243   -0.009342
244    0.003124
245   -0.030807
246   -0.054067
Name: Return, Length: 247, dtype: float64


Sheet name: NTPC
0      0.000000
1      0.010313
2      0.005117
3     -0.034493
4      0.021281
         ...
245    0.017673
246    0.003016
247   -0.004829
248    0.001512
249    0.002715
Name: Return, Length: 250, dtype: float64


Sheet name: IOCL
0      0.000000
1     -0.026103
2      0.004398
3      0.016862
4      0.002693
         ...
242   -0.009080
243   -0.015038
244    0.009634
245   -0.013851
246   -0.009342
Name: Return, Length: 247, dtype: float64


Sheet name: GAIL
0      0.000000
1     -0.009489
2     -0.006732
3     -0.022287
4      0.012284
         ...
245   -0.011784
246    0.021850
247    0.012052
248   -0.002085
249    0.000000
Name: Return, Length: 250, dtype: float64

In [ ]:
for sheet_name, df in data.items():
  df = df[['Day_of_week','Return']]
  excel[sheet_name]=df

excel['BSE']

     Day_of_week    Return
0              3  0.000000
1              0 -0.017553
2              1  0.000855
3              2  0.009313
4              3  0.001699
..           ...       ...
243            4 -0.004062
244            0  0.004024
245            1  0.006061
246            2  0.012696
247            3 -0.001970

[248 rows x 2 columns]

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
for sheet_name, df in data.items():
  df = df[['Day_of_week','Return']]
  days_dummies = pd.get_dummies(df['Day_of_week'], prefix='Day')
  df = df.drop(['Day_of_week'], axis=1)
  df = pd.concat([df, days_dummies], axis=1)
  excel[sheet_name]=df

excel['BSE']

       Return  Day_0  Day_1  Day_2  Day_3  Day_4
0    0.000000      0      0      0      1      0
1   -0.017553      1      0      0      0      0
2    0.000855      0      1      0      0      0
3    0.009313      0      0      1      0      0
4    0.001699      0      0      0      1      0
..        ...    ...    ...    ...    ...    ...
243 -0.004062      0      0      0      0      1
244  0.004024      1      0      0      0      0
245  0.006061      0      1      0      0      0
246  0.012696      0      0      1      0      0
247 -0.001970      0      0      0      1      0

[248 rows x 6 columns]

In [ ]:
X = excel['BSE'][['Day_0','Day_1','Day_2','Day_3','Day_4']]
X = sm.add_constant(X)
y = excel['BSE']['Return']

# Fit the regression model
model = sm.OLS(y, X).fit()

# Print the regression results
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                 Return   R-squared:                       0.027
Model:                            OLS   Adj. R-squared:                  0.011
Method:                 Least Squares   F-statistic:                     1.694
Date:                Thu, 07 Mar 2024   Prob (F-statistic):              0.152
Time:                        11:17:30   Log-Likelihood:                 792.01
No. Observations:                 248   AIC:                            -1574.
Df Residuals:                     243   BIC:                            -1556.
Df Model:                           4
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.0005      0.001      0.974      0.331      -0.001       0.002
Day_0         -0.0018      0.001     -1.408      0.160      -0.004       0.001
Day_1          0.0026      0.001      2.090      0.038       0.000       0.005
Day_2          0.0011      0.001      0.812      0.417      -0.001       0.004
Day_3          0.0002      0.001      0.121      0.904      -0.002       0.003
Day_4         -0.0016      0.001     -1.186      0.237      -0.004       0.001
==============================================================================
Omnibus:                       40.010   Durbin-Watson:                   1.922
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               91.375
Skew:                          -0.766   Prob(JB):                     1.44e-20
Kurtosis:                       5.549   Cond. No.                     5.25e+15
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 1.08e-29. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.

In [ ]:
X = excel['ONGC'][['Day_0','Day_1','Day_2','Day_3','Day_4']]
X = sm.add_constant(X)
y = excel['ONGC']['Return']

# Fit the regression model
model = sm.OLS(y, X).fit()

# Print the regression results
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                 Return   R-squared:                       0.012
Model:                            OLS   Adj. R-squared:                 -0.004
Method:                 Least Squares   F-statistic:                    0.7587
Date:                Thu, 07 Mar 2024   Prob (F-statistic):              0.553
Time:                        11:17:35   Log-Likelihood:                 594.21
No. Observations:                 247   AIC:                            -1178.
Df Residuals:                     242   BIC:                            -1161.
Df Model:                           4
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.0016      0.001      1.390      0.166      -0.001       0.004
Day_0          0.0033      0.003      1.209      0.228      -0.002       0.009
Day_1          0.0030      0.003      1.090      0.277      -0.002       0.009
Day_2         -0.0003      0.003     -0.120      0.905      -0.006       0.005
Day_3         -0.0022      0.003     -0.787      0.432      -0.008       0.003
Day_4         -0.0022      0.003     -0.756      0.450      -0.008       0.004
==============================================================================
Omnibus:                       49.221   Durbin-Watson:                   2.003
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              219.433
Skew:                           0.697   Prob(JB):                     2.24e-48
Kurtosis:                       7.402   Cond. No.                     4.79e+15
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 1.29e-29. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.

In [ ]:
X = excel['NTPC'][['Day_0','Day_1','Day_2','Day_3','Day_4']]
X = sm.add_constant(X)
y = excel['NTPC']['Return']

# Fit the regression model
model = sm.OLS(y, X).fit()

# Print the regression results
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                 Return   R-squared:                       0.028
Model:                            OLS   Adj. R-squared:                  0.012
Method:                 Least Squares   F-statistic:                     1.751
Date:                Thu, 07 Mar 2024   Prob (F-statistic):              0.139
Time:                        11:17:41   Log-Likelihood:                 686.81
No. Observations:                 250   AIC:                            -1364.
Df Residuals:                     245   BIC:                            -1346.
Df Model:                           4
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.0009      0.001      1.055      0.293      -0.001       0.002
Day_0          0.0014      0.002      0.716      0.474      -0.002       0.005
Day_1          0.0048      0.002      2.384      0.018       0.001       0.009
Day_2         -0.0015      0.002     -0.751      0.453      -0.005       0.002
Day_3         -0.0023      0.002     -1.178      0.240      -0.006       0.002
Day_4         -0.0015      0.002     -0.777      0.438      -0.005       0.002
==============================================================================
Omnibus:                       13.676   Durbin-Watson:                   2.092
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               22.286
Skew:                           0.327   Prob(JB):                     1.45e-05
Kurtosis:                       4.309   Cond. No.                     1.22e+16
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 2.02e-30. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.

In [ ]:
X = excel['IOCL'][['Day_0','Day_1','Day_2','Day_3','Day_4']]
X = sm.add_constant(X)
y = excel['IOCL']['Return']

# Fit the regression model
model = sm.OLS(y, X).fit()

# Print the regression results
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                 Return   R-squared:                       0.021
Model:                            OLS   Adj. R-squared:                  0.005
Method:                 Least Squares   F-statistic:                     1.313
Date:                Thu, 07 Mar 2024   Prob (F-statistic):              0.266
Time:                        11:17:42   Log-Likelihood:                 660.61
No. Observations:                 247   AIC:                            -1311.
Df Residuals:                     242   BIC:                            -1294.
Df Model:                           4
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.0011      0.001      1.191      0.235      -0.001       0.003
Day_0         -0.0032      0.002     -1.518      0.130      -0.007       0.001
Day_1          0.0035      0.002      1.651      0.100      -0.001       0.008
Day_2          0.0023      0.002      1.068      0.286      -0.002       0.007
Day_3         -0.0003      0.002     -0.119      0.905      -0.004       0.004
Day_4         -0.0013      0.002     -0.593      0.553      -0.006       0.003
==============================================================================
Omnibus:                        6.472   Durbin-Watson:                   1.976
Prob(Omnibus):                  0.039   Jarque-Bera (JB):                9.980
Skew:                          -0.069   Prob(JB):                      0.00681
Kurtosis:                       3.975   Cond. No.                     4.79e+15
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 1.29e-29. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.

In [ ]:
X = excel['GAIL'][['Day_0','Day_1','Day_2','Day_3','Day_4']]
X = sm.add_constant(X)
y = excel['GAIL']['Return']

# Fit the regression model
model = sm.OLS(y, X).fit()

# Print the regression results
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                 Return   R-squared:                       0.012
Model:                            OLS   Adj. R-squared:                 -0.004
Method:                 Least Squares   F-statistic:                    0.7635
Date:                Thu, 07 Mar 2024   Prob (F-statistic):              0.550
Time:                        11:17:46   Log-Likelihood:                 637.01
No. Observations:                 250   AIC:                            -1264.
Df Residuals:                     245   BIC:                            -1246.
Df Model:                           4
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.0002      0.001      0.166      0.868      -0.002       0.002
Day_0          0.0021      0.002      0.876      0.382      -0.003       0.007
Day_1          0.0024      0.002      0.965      0.336      -0.002       0.007
Day_2          0.0005      0.002      0.197      0.844      -0.004       0.005
Day_3         -0.0019      0.002     -0.782      0.435      -0.007       0.003
Day_4         -0.0029      0.002     -1.202      0.231      -0.008       0.002
==============================================================================
Omnibus:                       12.741   Durbin-Watson:                   2.052
Prob(Omnibus):                  0.002   Jarque-Bera (JB):               22.369
Skew:                          -0.269   Prob(JB):                     1.39e-05
Kurtosis:                       4.363   Cond. No.                     1.22e+16
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 2.02e-30. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.